version: '3.8'
services:
  mqtt:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    volumes:
      - "./mosquitto-data:/mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    depends_on:
      - mqtt
    ports:
      - 8080:8080
    environment:
      - TZ=${TIME_ZONE}
    devices:
      - /dev/ttyAMA0:/dev/ttyACM0

  hearthsensorlistener:
    container_name: hearth-sensor-listener
    image: registryhestia.azurecr.io/hearthsensorlistener:latest
    restart: unless-stopped
    depends_on:
      - mqtt
    volumes:
      - ./hearthlistener-data:/app/data
    environment:
      - mqtt_host=mqtt
      - box_id=${BOX_ID}
      - ACR_USERNAME=${REGISTRY_USR}
      - ACR_PASSWORD=${REGISTRY_PWD}

  hearthsensormanager:
    container_name: hearth-sensor-manager
    image: registryhestia.azurecr.io/hearthsensormanager:latest
    restart: unless-stopped
    depends_on:
      - mqtt
    volumes:
      - ./hearthmanager-data:/app/data
    environment:
      - mqtt_host=mqtt
      - box_id=${BOX_ID}
      - ACR_USERNAME=${REGISTRY_USR}
      - ACR_PASSWORD=${REGISTRY_PWD}

  hearthiotconnect:
    container_name: hearth-iot-connect
    image: registryhestia.azurecr.io/hearthiotconnect:latest
    restart: unless-stopped
    depends_on:
      - mqtt
    volumes:
      - ./hearthiotconnect-data:/app/data
    environment:
      - DeviceId=${BOX_ID}
      - HostName=${IOT_HOST}
      - SharedAccessKey=${IOT_TOKEN}
      - mqtt_host=mqtt
      - ACR_USERNAME=${REGISTRY_USR}
      - ACR_PASSWORD=${REGISTRY_PWD}

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    environment:
      DOCKER_CONFIG: /config
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/hearhRoot/docker:/config
    command: --interval 3600
