version: '3.8'
services:
  mqtt:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    volumes:
      - "./mosquitto-data:/mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    depends_on:
      - mqtt
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Stockholm
    devices:
      - /dev/ttyAMA0:/dev/ttyACM0

  hearthsensorlistener:
    container_name: hearth-sensor-listener
    image: registryhestia.azurecr.io/hearthsensorlistener:9837
    depends_on:
      - mqtt
    volumes:
      - ./hearthlistener-data:/app/data
    environment:
      - mqtt_host=mqtt
      - box_id=hearth_poc_1

  hearthiotconnect:
    container_name: hearth-iot-connect
    image: registryhestia.azurecr.io/hearthiotconnect:9838
    depends_on:
      - mqtt
    volumes:
      - ./hearthiotconnect-data:/app/data
    environment:
      - DeviceId=heart_poc_1
      - HostName=Unicorn-project-iot.azure-devices.net
      - SharedAccessKey=mnPLPzeSpXPjAzPLu+PUIkaVtSDF8XftM5IxXzBJGtM=
      - mqtt_host=mqtt



      
